[workspace]
resolver = "2"

members = [
  "nft-minter",
  "nft-minter/meta",
  "nft-minter-deployer",
  "nft-minter-deployer/meta",
  "royalties-handler",
  "royalties-handler/meta",
  "esdt-system-sc-mock",
  "esdt-system-sc-mock/meta"
]
