[package]
name = "nft-minter-deployer-meta"
version = "0.0.0"
authors = ["MultiversX <contact@multiversx.com>"]
edition = "2021"
publish = false
[dependencies.nft-minter-deployer]
path = ".."

[dependencies.multiversx-sc-meta]
version = "0.41.3"
