// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           12
// Async Callback (empty):               1
// Total number of exported functions:  14

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    nft_minter_deployer
    (
        init => init
        createNftMinter => create_nft_minter_endpoint
        upgradeNftMinter => upgrade_nft_minter_endpoint
        pauseNftMinter => pause_nft_minter
        resumeNftMinter => resume_nft_minter
        addAdminToNftMinterContract => add_admin_to_nft_minter_contract
        removeAdminToNftMinterContract => remove_admin_to_nft_minter_contract
        setNftMinterTemplateAddress => set_nft_minter_template_address
        setNftMinterCreationEnabled => set_nft_minter_creation_enabled
        getUserNftMinterContracts => user_nft_minter_contracts
        getAllNftMinterContracts => all_nft_minter_contracts
        getNftMinterTemplateAddress => nft_minter_template_address
        getNftMinterCreationEnabled => nft_minter_creation_enabled
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
