// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           14
// Async Callback (empty):               1
// Total number of exported functions:  16

#![no_std]
#![allow(internal_features)]
#![feature(lang_items)]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    royalties_handler
    (
        init => init
        getLastClaimEpoch => last_claim_epoch
        getShareholders => shareholders
        claimNftMinterPaymentsAndRoyalties => claim_nft_minter_payments_and_royalties
        getNftMinterScAddress => nft_minter_sc_address
        addShareholders => add_shareholders
        removeShareholders => remove_shareholders
        claimRewards => claim_rewards
        getClaimableEntryIdsForAddress => get_claimable_entry_ids_for_address
        claimableTokensForRewardEntry => get_claimable_tokens_for_reward_entry
        createNewRewardEntry => create_new_reward_entry
        getLastRewardEntryEpoch => last_reward_entry_epoch
        getLastEntryId => last_entry_id
        getClaimWhitelistForEntry => claim_whitelist_for_entry
        getTokenBalances => get_token_balances
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
