[package]
name = "esdt-system-sc-mock-meta"
version = "0.0.0"
authors = ["Dorin Marian Iancu <dorin.iancu@elrond.com>"]
edition = "2018"
publish = false
[dependencies.esdt-system-sc-mock]
path = ".."

[dependencies.multiversx-sc-meta]
version = "=0.41.3"
