name: On pull request, build contracts

on:
  pull_request:

permissions:
  contents: write

jobs:
  build:
    uses: multiversx/mx-sc-actions/.github/workflows/reproducible-build.yml@v3.0.0
    with:
      image_tag: v6.1.2
