name: On release, build contracts

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    uses: multiversx/mx-sc-actions/.github/workflows/reproducible-build.yml@v3.0.0
    with:
      image_tag: v6.1.2
      attach_to_existing_release: true
      skip_preliminary_checks: true
