name: On release, build contracts

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build:
    uses: multiversx/mx-sc-actions/.github/workflows/reproducible-build.yml@v4.2.1
    with:
      image_tag: v8.0.1
      attach_to_existing_release: true
      skip_preliminary_checks: true
